name: Integration Tests

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions:
  contents: read
  
jobs:

  integration:
    name: CloudEvents Integration Test
    strategy:
      matrix:
        # Only test one go version: the integration tests don't seem to pass if NATS runs more one running at a time.
        go-version: [1.23]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    services:
      kafka:
        image: lensesio/fast-data-dev
        env:
          ADV_HOST: localhost
        ports:
          - 9091:9091
          - 9092:9092

      kafka_confluent:
        image: confluentinc/confluent-local:7.6.0
        ports:
          - "9192:9192"
        env:
          KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:29192,PLAINTEXT_HOST://localhost:9192'
          KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:29193'
          KAFKA_LISTENERS: 'PLAINTEXT://localhost:29192,CONTROLLER://localhost:29193,PLAINTEXT_HOST://0.0.0.0:9192'

      natss:
        image: nats-streaming:0.22.1
        ports:
          - 4222:4222

      jetstream:
        image: bitnami/nats:latest
        env: 
          NATS_EXTRA_ARGS: "--jetstream --port 4223"
        ports:
          - 4223:4223

      amqp:
        image: bitnami/rabbitmq@sha256:e3adb8a61861a173312d5e1df6a5c211a3c6b5070b075fd31ae68c78906972ae # v4.1.0
        ports:
          - 5672:5672
      
      mqtt:
        image: eclipse-mosquitto:1.6
        ports:
          - 1883:1883

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: v2/go.sum
        id: go
        
      - name: Test
        env:
          TEST_AMQP_URI: "amqp://amqp"
        run: ./hack/integration-test.sh

